#!/bin/bash
set -euo pipefail

RUN_PARAMS="${RUN_PARAMS:-} --config-dir ${CONF_PATH}"

if [ "${METASEARCH_MIGRATE:-}" = "true" ]; then
  exec ./metasearch migrate $RUN_PARAMS "$@"
  exit $?
fi

# for backward compatibility reason, we use argument as command, only if it's an executable (and use it as satellite flags oterwise)
set +eo nounset
which "$1" > /dev/null
VALID_EXECUTABLE=$?
set -eo nounset

if [ $VALID_EXECUTABLE -eq 0 ]; then
  # this is a full command (what storj-up uses)
  exec "$@"
else
  # legacy, run-only parameters
  exec ./metasearch run $RUN_PARAMS "$@"
fi
